
SELECT *
FROM DBAMV.PACIENTE  , DBAMV.atendime
INNER JOIN DBAMV.PACIENTE ON DBAMV.PACIENTE.cd_paciente = DBAMV.ATENDIME.cd_paciente;


SELECT  PACIENTE.nm_paciente,   ATENDIME.cd_atendimento
FROM  DBAMV.PACIENTE, DBAMV.ATENDIME
WHERE DBAMV.PACIENTE.CD_PACIENTE = DBAMV.ATENDIME.CD_PACIENTE;


SELECT  PACIENTE.nm_paciente, PACIENTE.cd_paciente FROM PACIENTE
UNION ALL
SELECT  MEDICO.nm_medico, MEDICO.cd_medico FROM MEDICO
WHERE nm_paciente.nm_medico

SELECT * FROM  WHER

SELECT * FROM ALL_SOURCE WHERE Upper (TEXT) LIKE '%UPDATE%'


SELECT NM_PACIENTE
FROM PACIENTE
WHERE EXISTS (SELECT NM_MEDICO FROM MEDICO WHERE PACIENTE.NM_PACIENTE = MEDICO.NM_MEDICO )

SELECT nm_paciente
 FROM PACIENTE
 WHERE NM_paciente  = ANY (SELECT SN_DOADOR FROM PACIENTE WHERE sn_doador IS NOT NULL);

 SELECT SN_DOADOR FROM PACIENTE WHERE sn_doador IS NOT NULL

ALL_OBJECTS

ALL_TRIGGERS

alL_JOBS










